Source management sorting
Eyevinn/orchestration-gui pull request #3
Opened 2024-08-28 11:06 UTC by Saelmala

This PR:

- Adds a lastConnected to the Source dB schema, which updates on inventory syncing if the source is found in the api
- Adds functionality to the FilterDropdown to sort sources based on their lastConnected date, with a button to reverse the order of the sorting

No sorting selected (in this case, the 'reverse sort order' button is disabled):
<img src="https://github.com/user-attachments/assets/7f629623-be52-4934-8759-f21cea5c8f8a" width="500">

Sort on most recent is selected, with the reverse button pressed:
<img src="https://github.com/user-attachments/assets/7ec645f5-794c-4d83-a9c6-e8ddf6ac63c5" width="500">

2024-08-28 12:59 UTC, bwallberg requested changes
I think for this to feel complete we should add the "lastConnected" date to the inventory card. Difficult to make an educated decision since the information isn't available 🙈

2024-08-29 09:46 UTC, Saelmala commented
Added last connected date to the source card/ edit view:

<img src="https://github.com/user-attachments/assets/e51fa615-590f-4908-a965-8176b52638aa" width="400">

<img src="https://github.com/user-attachments/assets/b2997718-8a3f-4440-b393-b1b8bc111f0e" width="500">

2024-08-30 06:19 UTC, bwallberg commented on src/api/manager/job/syncInventory.ts
> +      lastConnected: new Date()
I just learned ( yesterday ) that the API now actually stores _some_ data about previously connected sources ( they used to just disappear...  ) so we have check the status here and only update lastConnected _if_ `status !== "gone"`.

2024-08-30 06:20 UTC, bwallberg requested changes
See comment about when to set lastConnected. The rest of code LGTM!

2024-08-30 07:38 UTC, bwallberg approved these changes
👏

2024-09-02 09:57 UTC, malmen237 approved these changes
LGTM

2024-09-02 13:03 UTC, LucasMaupin commented
LGTM

2024-09-02 13:07 UTC, merged